#if !defined(TRMNL_ERRORS)
#define TRMNL_ERRORS

enum trmnl_error {
  NO_ERROR = 0,
  MALLOC_FAILED,
  FS_FAIL,
  FILE_NOT_FOUND,
  SIZE_TOO_LARGE,
  SIZE_TOO_SMALL,
  IMAGE_CREATION_FAILED,
  IMAGE_STRUCTURE_CORRUPTED,
  IMAGE_FORMAT_UKNOWN,
  IMAGE_FORMAT_UNEXPECTED_SIGNATURE,
  IMAGE_FORMAT_UNSUPPORTED,
  IMAGE_INCOMPATIBLE,
  IMAGE_COLORS_INVALID,
  IMAGE_HEADER_INVALID,
  IMAGE_DECODE_FAIL
  };

#endif